"""Preference-rule extraction over the records since the last pass.

Copier-vendored from the agentic-engineering-template decision-memory
subtemplate — change it there, pull via `copier update`.

Records are what happened; the active preference set is what the next
session is told to expect. Extraction is the bridge, and without it the corpus
grows while the rule set does not — every record lands
`prediction_stream: cold` because no rule was there to drive it, and
the replay gate has nothing to measure.

**The watermark is a commit, not a file.** Every pass ends with a
`pref-extract:` commit, so "what is new" is everything added since the
last one — derived from history rather than tracked beside it. Nothing
to advance, nothing to keep in sync, nothing to conflict when two
branches run a pass at once, and the message carries what the pass
found.

Two properties fall out of deriving it rather than storing it:

- **It self-heals.** A session merged without a pass is not lost; the
  next pass simply reaches further back. A stored watermark that was
  never advanced would look identical to one with nothing to do.
- **Bootstrap is not a special case.** With no `pref-extract:` commit
  anywhere in history, the watermark is the beginning of the corpus, so
  the first pass covers everything by construction.

An EMPTY pass commits too. That is what makes detection reliable: a
pass that found nothing produces no proposal and no counter bump, so
keying the watermark on those would stall it every time extraction
legitimately had nothing to say — and `pref-confirm:` is generated by
`record.py submit` as well, which would move the watermark for a pass
that never ran. "Extraction ran and found nothing" is information; the
commit is where it goes.

Scope and evidence are different things, and conflating them is what
makes per-session extraction look wrong:

- **Scope** — what the pass must act on — is the records since the
  watermark.
- **Evidence** — what the pass may reason from — is the WHOLE corpus.
  Cross-session repetition is the signal a single session cannot see,
  so the batch ships the full history alongside the new records. A
  pattern is not new because this session is the first to show it.

This module is the read side. It emits the batch as JSON and the skill
(`.agents/skills/extract-preferences/SKILL.md`) does the judgement —
the same split as the replay harness, and for the same reason: the
decisions live in pure functions that CI can test, and the part needing
a model stays outside them.

**Extraction never writes to `decisions/`.** It reads history and
proposes rules; the append-only guarantee is not negotiated here.

Stdlib only. Usage:

    python .github/store/extraction.py status
    python .github/store/extraction.py batch --out batch.json
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

DECISIONS_DIR = "decisions"

# Queues, most informative first. A record lands in exactly one.
QUEUE_CORRECTIONS = "corrections"
QUEUE_MISSES = "misses"
QUEUE_REFINEMENTS = "refinements"
QUEUE_CONFIRMATIONS = "confirmations"
QUEUES = (QUEUE_CORRECTIONS, QUEUE_MISSES, QUEUE_REFINEMENTS, QUEUE_CONFIRMATIONS)

PREFERENCE_DRIVEN = "preference-driven"

# The commit that closes a pass, and therefore the watermark. A
# dedicated type rather than `chore(extraction):` so the watermark is a
# typed event that cannot be produced by accident — detection
# reliability is the entire reason this is a commit and not a file.
EXTRACTION_PREFIX = "pref-extract:"

# git log --grep is a POSIX BASIC regex over the whole message. Written
# literally rather than through re.escape, which emits `\-` — undefined
# in BRE, where a stray backslash-punctuation is not portably a literal.
# The prefix contains no BRE metacharacters, so only the anchor is
# needed; it pins the match to a line start so a subject matches and a
# mention inside a body does not.
_EXTRACTION_GREP = "^pref-extract:"


def prediction_option(record: dict) -> dict | None:
    """The option carrying the prediction role, if any.

    Exactly one option carries it per the record contract; this returns
    the first, so a malformed record degrades to a wrong-but-harmless
    answer instead of an exception.
    """
    for option in record.get("options") or []:
        if not isinstance(option, dict):
            continue
        if "prediction" in str(option.get("role") or ""):
            return option
    return None


def is_rule_driven_acceptance(record: dict) -> bool:
    """Did this record's rules merely confirm their own recommendation?

    A rule that cited itself into slot 1 and got slot 1 chosen has
    produced no independent evidence: the recommendation caused the
    choice it is now counted as predicting. Extraction flags these and
    never strengthens the rule on them.
    """
    option = prediction_option(record)
    if option is None or not option.get("rules_cited"):
        return False
    return option.get("slot") == record.get("chosen_slot")


def queue_for(record: dict) -> str:
    """Which extraction queue a record belongs in.

    Corrections first — a `"N, but actually because…"` ruling carries
    the decider's own reason where the model's guess was wrong, which is
    the only place the corpus records a reason nobody inferred. Misses
    second: each one must refine a rule, split one, or spawn a
    candidate. Then refinements, then plain confirmations.
    """
    if record.get("correction") is True:
        return QUEUE_CORRECTIONS
    outcome = record.get("outcome")
    if outcome == "miss":
        return QUEUE_MISSES
    if outcome in ("refined", "near-tie"):
        return QUEUE_REFINEMENTS
    return QUEUE_CONFIRMATIONS


def summarise(record: dict) -> dict:
    """One record, reduced to what a rule-extraction pass reads.

    Unlike the replay harness this deliberately keeps the output side:
    extraction is looking at what the decider actually did and why,
    which is exactly the half replay has to mask.
    """
    option = prediction_option(record)
    return {
        "id": record.get("id"),
        "date": record.get("date"),
        "project": record.get("project"),
        "question": record.get("question"),
        "chosen": record.get("chosen"),
        "chosen_slot": record.get("chosen_slot"),
        "operative_reason": record.get("operative_reason"),
        "operative_reason_source": record.get("operative_reason_source"),
        "correction": bool(record.get("correction")),
        "outcome": record.get("outcome"),
        "prediction_stream": record.get("prediction_stream"),
        "rules_cited": (option or {}).get("rules_cited") or [],
        "rule_driven_acceptance": is_rule_driven_acceptance(record),
        "rejections": [
            {
                "option": rejection.get("option"),
                "reason": rejection.get("reason"),
                "status": rejection.get("status"),
                "reason_source": rejection.get("reason_source"),
            }
            for rejection in record.get("rejections") or []
            if isinstance(rejection, dict)
        ],
        "supersedes": record.get("supersedes"),
        "related": record.get("related") or [],
        "notes": record.get("notes"),
    }


def build_batch(records: list[dict], scope: set[str]) -> dict:
    """The records since the watermark, queued, with history as evidence.

    ``records`` is the WHOLE corpus; ``scope`` names the records since
    the watermark. Everything outside the scope ships as `history` — a
    pass that cannot see it would call a pattern new the third time it
    appeared.
    """
    in_scope = [r for r in records if str(r.get("id") or "") in scope]
    history = [r for r in records if str(r.get("id") or "") not in scope]

    queues: dict[str, list[dict]] = {name: [] for name in QUEUES}
    for record in in_scope:
        queues[queue_for(record)].append(summarise(record))

    flagged = [
        summary["id"]
        for queue in queues.values()
        for summary in queue
        if summary["rule_driven_acceptance"]
    ]
    return {
        "scope": sorted(scope),
        "count": len(in_scope),
        "history_count": len(history),
        "instructions": (
            "Work the queues in order. Judge each pattern against the "
            "WHOLE corpus, not just the scope: `history` is here because "
            "cross-session repetition is the evidence a single session "
            "cannot see, and a pattern is not new because this session is "
            "the first to show it. For each candidate choose EXACTLY one "
            "outcome: confirm an existing rule (counter bump), flag drift "
            "against one (propose conditionalize or retire — never a "
            "silent overwrite), or propose a new rule in conditional, "
            "falsifiable form. A miss that does none of the three is "
            "logged as unexplained; unexplained is a state, not a "
            "silence. Rules listed under rule_driven_acceptances have "
            "confirmed only their own recommendation and carry no "
            "independent evidence — never strengthen them on those "
            "records."
        ),
        "queues": {name: queues[name] for name in QUEUES},
        "queue_counts": {name: len(queues[name]) for name in QUEUES},
        "rule_driven_acceptances": flagged,
        "preference_driven_count": sum(
            1
            for queue in queues.values()
            for summary in queue
            if summary["prediction_stream"] == PREFERENCE_DRIVEN
        ),
        "history": [summarise(record) for record in history],
    }


def check_pass(base: str, root: str = ".") -> list[str]:
    """Guard check: a PR adding records must close with a pass.

    Purely positional — the extraction commit's PLACE in history is its
    claim, so there is nothing to enumerate, nothing to keep in sync
    with the diff, and nothing that can be copied from another branch.
    Two things are checked:

    1. A branch that adds records contains a `pref-extract:` commit.
    2. No record is added AFTER it. Extraction is the last step of the
       pass; a record landing later is a record the pass never saw.

    A branch that adds no records needs no pass and is not checked —
    running extraction there is allowed, just never required.
    """
    added = added_since(base, root, three_dot=True)
    if not added:
        return []

    pass_sha = last_extraction_commit(f"{base}..HEAD", root)
    if pass_sha is None:
        return [
            f"this PR adds {len(added)} decision record(s) but contains no "
            f"{EXTRACTION_PREFIX} commit. Run `/extract-preferences` and commit "
            "the pass — a pass that found nothing still commits, because a "
            "skipped one leaves no trace and the next pass has no way to know "
            "it was skipped"
        ]

    late = added_since(pass_sha, root)
    if late:
        return [
            f"{len(late)} record(s) were added after the {EXTRACTION_PREFIX} "
            f"commit {pass_sha[:9]}: {', '.join(sorted(late))} — extraction is "
            "the last step of the pass, so re-run it and re-commit"
        ]
    return []


def _git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=True)
    return result.stdout


def _is_shallow(root: str) -> bool:
    return _git("-C", root, "rev-parse", "--is-shallow-repository").strip() == "true"


def _require_complete_history(root: str) -> None:
    """Refuse to derive a watermark from a truncated history.

    Deriving the watermark instead of storing it buys self-healing: a
    session merged without a pass is not lost, because the next pass
    reaches further back. That property depends entirely on the history
    being complete. Under a shallow clone the walk stops at the boundary
    and returns None — indistinguishable from "no pass has ever run",
    and wrong by however much was cut off.

    This is the normal state, not an exotic one: the grilling skill
    tells sessions to shallow-clone the store.

    Refusing rather than fetching: a `status` command that silently
    reaches the network is a surprise, and the remedy is one command the
    caller can run deliberately.
    """
    if _is_shallow(root):
        raise SystemExit(
            "refusing to derive the watermark: this is a shallow clone, so "
            "`pref-extract:` commits older than the boundary are invisible and "
            "the scope would be overstated by however much history is missing. "
            "Run `git fetch --unshallow` and try again."
        )


def last_extraction_commit(rev_range: str = "HEAD", root: str = ".") -> str | None:
    """SHA of the newest `pref-extract:` commit in `rev_range`, or None.

    None means no pass has ever run over that range, which is not an
    error state: it is what the first pass on a fresh corpus sees, and
    it is why bootstrap needs no special mode.

    That reading is only sound over a COMPLETE history, so a shallow
    clone is refused rather than reported as a bootstrap.
    """
    _require_complete_history(root)
    out = _git(
        "-C",
        root,
        "log",
        "--format=%H",
        "--grep",
        _EXTRACTION_GREP,
        "-n",
        "1",
        rev_range,
    ).strip()
    return out or None


def added_since(
    since: str | None, root: str = ".", three_dot: bool = False
) -> set[str]:
    """Record IDs added after `since`, or the whole corpus when None.

    The IDs are filename stems, which the record contract pins equal to
    the `id` field — so this needs no file reads and stays correct for a
    record whose JSON is malformed.

    `three_dot` compares against the merge base instead of the tip, which
    is what a PR diff means; the watermark walk wants the plain
    two-dot form, since a pass covers everything that has landed since
    it regardless of which branch it landed on.
    """
    if since is None:
        return (
            {
                name[: -len(".json")]
                for name in os.listdir(os.path.join(root, DECISIONS_DIR))
                if name.endswith(".json") and not name.startswith(".")
            }
            if os.path.isdir(os.path.join(root, DECISIONS_DIR))
            else set()
        )

    separator = "..." if three_dot else ".."
    diff = _git(
        "-C",
        root,
        "diff",
        "--name-only",
        "--diff-filter=A",
        f"{since}{separator}HEAD",
        "--",
        f"{DECISIONS_DIR}/",
    )
    ids = set()
    for line in diff.splitlines():
        name = os.path.basename(line.strip())
        if name.endswith(".json"):
            ids.add(name[: -len(".json")])
    return ids


def scope_ids(root: str = ".") -> tuple[set[str], str | None]:
    """The records this pass must act on, and the watermark it used."""
    watermark = last_extraction_commit("HEAD", root)
    return added_since(watermark, root), watermark


def load_records(root: str = ".") -> list[dict]:
    """Read `decisions/` without importing the replay harness.

    Kept local so extraction stays usable in a store whose replay
    harness is mid-update; the corpus layout is fixed by the record
    contract, not by that module.
    """
    directory = os.path.join(root, DECISIONS_DIR)
    records: list[dict] = []
    if not os.path.isdir(directory):
        return records
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".json") or name.startswith("."):
            continue
        with open(os.path.join(directory, name), encoding="utf-8") as handle:
            records.append(json.load(handle))
    return records


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repo root (default: cwd)")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("status", help="how many records are waiting for a pass")
    batch = sub.add_parser("batch", help="emit the prioritized batch")
    batch.add_argument("--out")

    args = parser.parse_args(argv)

    records = load_records(args.root)
    in_scope, watermark = scope_ids(args.root)
    payload = build_batch(records, in_scope)
    payload["watermark"] = watermark

    if args.command == "status":
        since = f"{watermark[:9]}" if watermark else "the beginning of the corpus"
        print(
            f"extraction: {payload['count']} record(s) since {since}, "
            f"{payload['history_count']} already covered "
            f"({payload['queue_counts']})"
        )
        return 0

    rendered = json.dumps(payload, indent=2, ensure_ascii=False)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(rendered + "\n")
        print(f"wrote {args.out}")
    else:
        print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
